---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo "selamat datang bangsaaaattt"
- name: input
  image: alpine
  command:
  - echo "masukin dong sayang"
