---
kind: pipeline
type: docker
name: default

steps:
- name: fetch
  image: alpine:git
  commands:
  - git fetch -a

- name: coverage test
  command:
  - echo "go test"

- name: building
  command:
  - echo "go build"

- name: deploy
  command:
  - echo "fab deploy -R production"
