pipeline:
  fetch:
    image: alpine
    commands: echo "fetching"
  coverage test:
    image: alpine
    commands: echo "go test"
  build:
    image: alpine
    commands: echo "go build"
  run:
    image: alpine
    commands: echo "go run"
  build docker:
    image: alpine
    commands: echo "docker build -t ."
  deploy:
    image: alpine
    commands: echo "fab deploy -R production"
   
